//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schmidt.Softplan.TechnicalEvaluation.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TechnicalEvaluationExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TechnicalEvaluationExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schmidt.Softplan.TechnicalEvaluation.Common.Resources.TechnicalEvaluationExceptio" +
                            "ns", typeof(TechnicalEvaluationExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF não é válido..
        /// </summary>
        public static string CPFInvalidException {
            get {
                return ResourceManager.GetString("CPFInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF é obrigatório..
        /// </summary>
        public static string CPFIsRequiredException {
            get {
                return ResourceManager.GetString("CPFIsRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail não é válido..
        /// </summary>
        public static string EmailInvalidException {
            get {
                return ResourceManager.GetString("EmailInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de distribuição não pode ser posterior a data atual..
        /// </summary>
        public static string ProcessoDateDistribuicaoException {
            get {
                return ResourceManager.GetString("ProcessoDateDistribuicaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição não pode teer mais de {0} caracteres..
        /// </summary>
        public static string ProcessoDescricaoMaxLengthException {
            get {
                return ResourceManager.GetString("ProcessoDescricaoMaxLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo está com a situação finalizada..
        /// </summary>
        public static string ProcessoIsFinalizedSituacaoException {
            get {
                return ResourceManager.GetString("ProcessoIsFinalizedSituacaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um processo com este número..
        /// </summary>
        public static string ProcessoNumeroProcessoUnificadoAlreadyExistisException {
            get {
                return ResourceManager.GetString("ProcessoNumeroProcessoUnificadoAlreadyExistisException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de processo unificado precisa {0} catacteres..
        /// </summary>
        public static string ProcessoNumeroProcessoUnificadoLengthException {
            get {
                return ResourceManager.GetString("ProcessoNumeroProcessoUnificadoLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de processo unificado é obrigatório..
        /// </summary>
        public static string ProcessoNumeroProcessoUnificadoNullException {
            get {
                return ResourceManager.GetString("ProcessoNumeroProcessoUnificadoNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasta física cliente não pode ter mais de {0} caracteres..
        /// </summary>
        public static string ProcessoPastaFisicaClienteMaxLengthException {
            get {
                return ResourceManager.GetString("ProcessoPastaFisicaClienteMaxLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não pode informar mais de uma vez um responsável..
        /// </summary>
        public static string ProcessoResponsavelDuplicatedException {
            get {
                return ResourceManager.GetString("ProcessoResponsavelDuplicatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório informar um responsável..
        /// </summary>
        public static string ProcessoResponsavelIsRequiredException {
            get {
                return ResourceManager.GetString("ProcessoResponsavelIsRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não pode informar mais de {0} responsáveis..
        /// </summary>
        public static string ProcessoResponsavelMaxLengthException {
            get {
                return ResourceManager.GetString("ProcessoResponsavelMaxLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação é obrigatório..
        /// </summary>
        public static string ProcessoSituacaoException {
            get {
                return ResourceManager.GetString("ProcessoSituacaoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um responsável com este CPF..
        /// </summary>
        public static string ResponsavelCPFAlreadyExistsException {
            get {
                return ResourceManager.GetString("ResponsavelCPFAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail é obrigatório..
        /// </summary>
        public static string ResponsavelEmailIsRequiredException {
            get {
                return ResourceManager.GetString("ResponsavelEmailIsRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail não pode ter mais de {0} caracteres..
        /// </summary>
        public static string ResponsavelEmailMaxLengthException {
            get {
                return ResourceManager.GetString("ResponsavelEmailMaxLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do responsável é obrigatório..
        /// </summary>
        public static string ResponsavelNomeIsRequiredException {
            get {
                return ResourceManager.GetString("ResponsavelNomeIsRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome não pode ter mais de {0} caracteres..
        /// </summary>
        public static string ResponsavelNomeMaxLengthException {
            get {
                return ResourceManager.GetString("ResponsavelNomeMaxLengthException", resourceCulture);
            }
        }
    }
}
